version: 1.0.{build}
image:
- Visual Studio 2017
- Ubuntu1804
install:
- cmd: cinst innosetup
- sh: apt-get install -y libtbb-dev
- git submodule update --init --recursive
environment:
  matrix:
  - {}
build_script:
- cmd: >-
    buildWindows.bat
- sh: >-
    cd third_party/flatbuffers
    cmake -S . -B LinuxBuilds
    cmake --build LinuxBuilds
    cd ../..
    cmake -S . -B builds
    cmake --build builds
    