# I looked at https://github.com/microsoft/cpprestsdk/blob/master/azure-pipelines.yml
# But this shows how to do this proper: https://github.com/surge-synthesizer/tuning-workbench-synth/blob/master/azure-pipelines.yml

jobs:
  - job: Build
    strategy:
      matrix:
        mac:
          imageName: 'macos-10.14'
          isMac: True          
        win2019:
          imageName: 'windows-2019'
          isWindows2019: True
          isWindows: True
        linux:
          imageName: 'ubuntu-18.04'
          isLinux: True
        win2019_DS:
          imageName: 'windows-2019'
          isWindows2019: True
          isWindows: True
          isDigitalStage: True
        
    pool:
      vmImage: $(imageName)
    steps:
    # Disable automatic line ending conversion, which is enabled by default on
    # Azure's Windows image. Having the conversion enabled caused cpplint of SQlite to fail on Windows
    - bash: git config --global core.autocrlf false
      displayName: "Disable git automatic line ending conversion"
    - bash: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev pkg-config libasound2-dev libgtk-3-dev libwebkit2gtk-4.0-dev libglew-dev libjack-dev libncurses5-dev
        apt list --installed
      displayName: Prepare Linux Host
      condition: variables.isLinux
    - script: git submodule update --init --recursive
      displayName: Checking out submodules

    # Windows runs CMake tasks
    - task: NuGetCommand@2
      displayName: Installing Innosetup
      inputs:
        command: restore
        restoreSolution: $(System.DefaultWorkingDirectory)/packages.config
        restoreDirectory: third_party
      condition: variables.isWindows
    - script: |
        pip3 install wheel setuptools
        pip3 install conan
        conan --version
        conan install -if Builds\Windows -s build_type=RelWithDebInfo --build missing .
      condition: variables.isWindows
    - task: CMake@1
      displayName: Configuring CMake for Flatbuffers
      inputs:
        workingDirectory: 'third_party/flatbuffers'
        cmakeArgs: '-S . -B Builds -G "Visual Studio 16 2019" -A x64'
      condition: variables.isWindows2019
    - task: CMake@1
      displayName: Running CMake build for Flatbuffers
      inputs:
        workingDirectory: 'third_party/flatbuffers'
        cmakeArgs: '--build Builds --config RelWithDebInfo'
      condition: variables.isWindows
    - task: CMake@1
      displayName: Configuring CMake for Windows
      inputs:        
        workingDirectory: $(Build.SourcesDirectory)
        cmakeArgs: '-S . -B Builds\Windows -G "Visual Studio 16 2019" -A x64 -DDIGITAL_STAGE_BRANDING=${{variables.isDigitalStage}}'
      condition: ${{ variables.isWindows2019 && !variables.isDigitalStage }}
    - task: CMake@1
      displayName: Configuring CMake for Windows (DigitalStage)
      inputs:        
        workingDirectory: $(Build.SourcesDirectory)
        cmakeArgs: '-S . -B Builds\Windows -G "Visual Studio 16 2019" -A x64 -DDIGITAL_STAGE_BRANDING=${{variables.isDigitalStage}}'
      condition: ${{ variables.isWindows2019 && variables.isDigitalStage }}
    - task: CMake@1
      displayName: Running CMake build for Windows
      inputs:
        workingDirectory: $(Build.SourcesDirectory)
        cmakeArgs: '--build Builds\Windows --config RelWithDebInfo'
      condition: variables.isWindows

    - publish: $(System.DefaultWorkingDirectory)/Builds/Windows/Client/jammernetz_setup_2.1.3.exe
      displayName: Publish Windows Installer
      artifact: WindowsInstaller
      condition: variables.isWindows2019

    # Linux uses bash to run CMake directly
    - bash: |
        cd third_party/flatbuffers 
        cmake -S . -B LinuxBuilds
        cmake --build LinuxBuilds
        cd ../.. 
        cd third_party/sentry-native
        cmake -S . -B builds -DSENTRY_BACKEND=crashpad
        cmake -DCMAKE_INSTALL_PREFIX=./install --build builds --target install 
        cd ../..
        cmake -S . -B builds 
        cmake --build builds
      displayName: Build with CMake for Linux
      condition: variables.isLinux
      
    # Mac build uses bash as well
    # No need to brew icu4c cmake as they are already present on Azure mac
    - bash: |
        brew install cmake gtk+3 glew
        cd third_party/flatbuffers
        cmake -S . -B LinuxBuilds -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build LinuxBuilds -- -j8
        cd ../..
        cmake -S . -B Builds/macOS -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build Builds/macOS -- -j8
        VERBOSE=1 cmake --build Builds/macOS --target package -- -j8 
      displayName: Build with CMake for Mac
      condition: variables.isMac
      
    - publish: $(System.DefaultWorkingDirectory)/Builds/macOS/JammerNetz-2.1.3-Darwin.dmg 
      displayName: Publish Mac Installer
      artifact: MacInstaller
      condition: variables.isMac
        
