name: Ubuntu Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Disable git automatic line ending conversion
      run: git config --global core.autocrlf false

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake libncurses-dev libglew-dev libncurses5-dev nlohmann-json3-dev
        sudo apt-get install -y libcurl4-openssl-dev pkg-config libasound2-dev libjack-dev
        sudo apt-get install -y libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype-dev libfontconfig1-dev libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libglu1-mesa-dev mesa-common-dev

    - name: Build Flatbuffers and Sentry
      run: |
        cmake --version
        cd third_party/flatbuffers
        cmake -S . -B LinuxBuilds
        cmake --build LinuxBuilds
        cd ../..
        cd third_party/sentry-native
        cmake -S . -B builds -DSENTRY_BACKEND=crashpad -DCMAKE_INSTALL_PREFIX=./install -DBUILD_JAMMERNETZ_CLIENT=OFF
        cmake --build builds --target install
        cd ../..

    - name: Build with CMake
      run: |
        cmake -S . -B builds
        cmake --build builds
