name: Windows Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Disable git automatic line ending conversion
      run: git config --global core.autocrlf false

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install InnoSetup
      run: |
        nuget restore $(System.DefaultWorkingDirectory)/packages.config -PackagesDirectory third_party

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        pip install wheel setuptools conan

    - name: Run Conan
      run: |
        conan profile detect
        conan install -of Builds\Windows -s build_type=RelWithDebInfo --build missing .

    - name: Configure CMake for Flatbuffers
      run: |
        cmake -S third_party/flatbuffers -B third_party/flatbuffers/Builds -G "Visual Studio 16 2019" -A x64

    - name: Build Flatbuffers
      run: |
        cmake --build third_party/flatbuffers/Builds --config RelWithDebInfo

    - name: Configure CMake for Windows
      run: |
        cmake -S . -B Builds\Windows -G "Visual Studio 16 2019" -A x64

    - name: Build Windows
      run: |
        cmake --build Builds\Windows --config RelWithDebInfo

    - name: Upload Windows Installer
      uses: actions/upload-artifact@v4
      with:
        name: WindowsInstaller
        path: Builds/Windows/Client/jammernetz_setup_2.3.0.exe
